/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: ada8dccaa2c82eb98371c04ad794399e)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	PUBLIC_SITE_URL: string;
	PUBLIC_SITE_INDEXABLE: string;
	PUBLIC_ANALYTICS_PROVIDER: string;
}
declare namespace Cloudflare {
	interface TestEnv {
		ASSETS: Fetcher;
		PUBLIC_SITE_URL: string;
		PUBLIC_SITE_INDEXABLE: string;
		PUBLIC_ANALYTICS_PROVIDER: string;
	}
	interface LighthouseEnv {
		ASSETS: Fetcher;
		PUBLIC_SITE_URL: string;
		PUBLIC_SITE_INDEXABLE: string;
		PUBLIC_ANALYTICS_PROVIDER: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_SITE_URL" | "PUBLIC_SITE_INDEXABLE" | "PUBLIC_ANALYTICS_PROVIDER">> {}
}
