export const publicRoutes = [
  '/',
  '/services/',
  '/services/full-service-planning-design/',
  '/services/partial-planning/',
  '/services/event-management-coordination/',
  '/events/weddings/',
  '/events/baby-bridal-showers/',
  '/events/birthdays-milestones/',
  '/events/kids-parties/',
  '/events/corporate-brand-events/',
  '/celebrations/',
  '/process/',
  '/about/',
  '/trusted-creative-network/',
  '/journal/',
  '/contact/',
  '/for-vendors/',
  '/privacy/',
  '/terms/',
  '/accessibility/',
] as const;

export const indexableRoutes = [
  '/',
  '/services/',
  '/events/weddings/',
  '/events/baby-bridal-showers/',
  '/events/birthdays-milestones/',
  '/events/kids-parties/',
  '/events/corporate-brand-events/',
  '/celebrations/',
  '/process/',
  '/about/',
  '/trusted-creative-network/',
  '/contact/',
  '/for-vendors/',
  '/accessibility/',
] as const;
